apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: pavelsidorovich/config-server:1.1
          ports:
            - containerPort: 8888
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 60
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8888
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 60
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: config-server-service
spec:
  selector:
    app: config-server
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
