apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-app-deployment
  labels:
    app: common-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common-app
  template:
    metadata:
      labels:
        app: common-app
    spec:
      containers:
        - name: common-app
          image: pavelsidorovich/common-service:1.2
          ports:
            - containerPort: 8080
          env:
            - name: spring.profiles.active
              value: docker
            - name: spring.config.import
              value: configserver:http://config-server-service:8888
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 60
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 60
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: common-app-service
spec:
  selector:
    app: common-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
