apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app-deployment
  labels:
    app: order-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-app
  template:
    metadata:
      labels:
        app: order-app
    spec:
      containers:
        - name: order-app
          image: pavelsidorovich/order-service:1.0
          ports:
            - containerPort: 8080
          env:
            - name: spring.profiles.active
              value: docker
            - name: spring.config.import
              value: configserver:http://config-server-service:8888
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 20
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 20
            httpGet:
              path: /actuator/health/readiness
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: order-app-service
spec:
  selector:
    app: order-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
